[workspace]
members = ["crates/commit-info", "crates/commit-pinned"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
