[package]
name = "commit-pinned"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
commit-info = { path = "../info" }
serde.workspace = true

[dev-dependencies]
serde_json = "1"
