[package]
name = "commit-info"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
sha2.workspace = true
const-str = "0.5"

[dev-dependencies]
serde_json = "1"

[build-dependencies]
git2 = "0.19"
sha2 = "0.10"
hex = "0.4"
